### PR TITLE
Fix/3.2.x/exogtn 1173

### PR DESCRIPTION
**Pull request by mto**
Encrypt rememberme password token

### CODE REVIEW

**Comment by trongtt** [comment]
BTW, i have learnt from internet that using AES is much better than DES which is being used by default.

And here is the summary :

DES is really old while AES is relatively new
DES is breakable while AES is still unbreakable
DES uses a much smaller key size compared to AES
DES uses a smaller block size compared to AES
DES uses a balanced Feistel structure while AES uses substitution-permutation

wdyt ?

**Comment by mto** [comment]
We should make a comparison based on following factors:
1. The 'practical security' of algorithm.
2. The length of encrypted password.

Java Cryptography Library supports both AES and DES algorithms, so it's not a big deal to switch between them.

**Comment by trongtt** [comment]
ok. so could you please investigate more about this to make sure that we are going to provide the best one from beginning by default.

**Comment by mto** [comment]
AES 's encrypted password size is twice larger than DES 's. So AES is acceptable to encrypt the user password.

The keysize is primary factor that makes AES (keysize = 128/192/256)more secure than DES (keysize = 56)

**Comment by trongtt** [comment]
very cool and thanks for your quick investigation.

could you update the patch for this change ?

**Pull request closed without merging**
